version: "3.9"

services:
  localstack:
    container_name: freelancer-ledger-localstack
    image: localstack/localstack:3.8
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=0
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true